/**
 * Mock seed data for Community ConnectHub (Madang Province, PNG).
 * Used for local development and demo environments.
 */

export const ROLE_DASHBOARD_PATHS = {
  resident: '/dashboard/resident',
  councillor: '/dashboard/councillor',
  wdc_chairman: '/dashboard/wdc-chairman',
  llg_admin: '/dashboard/llg-admin',
  dda_officer: '/dashboard/dda-officer',
  provincial_admin: '/dashboard/provincial',
  system_admin: '/dashboard/system-admin',
};

export const PROJECT_STATUSES = [
  'Pending WDC',
  'Pending LLG',
  'Pending District',
  'Pending Provincial',
  'Funded',
  'In Progress',
  'Completed',
];

export const REQUEST_STATUSES = ['Pending', 'In Progress', 'Resolved', 'Rejected'];

export const MEETING_STATUSES = ['Scheduled', 'In Progress', 'Completed', 'Cancelled'];

export const RESOLUTION_STATUSES = ['Pending', 'Approved', 'Rejected'];

const TEST_PASSWORD = 'TestPass1!';

export const MOCK_USERS = [
  {
    id: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    username: '210529',
    email: 'lisa@test.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'Lisa',
    lastName: 'Numbunda',
    name: 'Lisa Numbunda',
    phone: '+675 7123 4529',
    ward: 'Ward 5 Nabasa',
    nid: '1234567890',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-06-12T08:30:00.000Z',
  },
  {
    id: 'usr-b2c3d4e5-f6a7-8901-bcde-f12345678901',
    username: '300001',
    email: 'councillor@test.com',
    password: TEST_PASSWORD,
    role: 'councillor',
    firstName: 'James',
    lastName: 'Kila',
    name: 'James Kila',
    phone: '+675 7234 1001',
    ward: 'Ward 5 Nabasa',
    nid: '1234567891',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-05-01T09:00:00.000Z',
  },
  {
    id: 'usr-c3d4e5f6-a7b8-9012-cdef-123456789012',
    username: '300002',
    email: 'wdc@test.com',
    password: TEST_PASSWORD,
    role: 'wdc_chairman',
    firstName: 'Peter',
    lastName: 'Yamau',
    name: 'Peter Yamau',
    phone: '+675 7345 2002',
    ward: 'Ward 5 Nabasa',
    nid: '1234567892',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-04-15T10:15:00.000Z',
  },
  {
    id: 'usr-d4e5f6a7-b8c9-0123-def0-234567890123',
    username: '400001',
    email: 'llg@test.com',
    password: TEST_PASSWORD,
    role: 'llg_admin',
    firstName: 'Sarah',
    lastName: 'Mathew',
    name: 'Sarah Mathew',
    phone: '+675 7456 3001',
    ward: 'Nabasa LLG',
    nid: '1234567893',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-03-20T11:00:00.000Z',
  },
  {
    id: 'usr-e5f6a7b8-c9d0-1234-ef01-345678901234',
    username: '400002',
    email: 'dda@test.com',
    password: TEST_PASSWORD,
    role: 'dda_officer',
    firstName: 'Michael',
    lastName: 'Taki',
    name: 'Michael Taki',
    phone: '+675 7567 4002',
    ward: 'Madang District',
    nid: '1234567894',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-03-10T08:45:00.000Z',
  },
  {
    id: 'usr-f6a7b8c9-d0e1-2345-f012-456789012345',
    username: '500001',
    email: 'provincial@test.com',
    password: TEST_PASSWORD,
    role: 'provincial_admin',
    firstName: 'Grace',
    lastName: 'Kaupa',
    name: 'Grace Kaupa',
    phone: '+675 7678 5001',
    ward: 'Madang Provincial Administration',
    nid: '1234567895',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-02-28T14:20:00.000Z',
  },
  {
    id: 'usr-a7b8c9d0-e1f2-3456-0123-567890123456',
    username: '600001',
    email: 'admin@test.com',
    password: TEST_PASSWORD,
    role: 'system_admin',
    firstName: 'Admin',
    lastName: 'User',
    name: 'Admin User',
    phone: '+675 7789 6001',
    ward: 'System Administration',
    nid: '1234567896',
    isApproved: true,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2025-01-15T07:00:00.000Z',
  },
  {
    id: 'usr-b8c9d0e1-f2a3-4567-1234-678901234567',
    username: '210601',
    email: 'john.sare@example.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'John',
    lastName: 'Sare',
    name: 'John Sare',
    phone: '+675 7123 4601',
    ward: 'Ward 3 Kuluguma',
    nid: '1234567897',
    isApproved: false,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2026-01-18T06:45:00.000Z',
  },
  {
    id: 'usr-c9d0e1f2-a3b4-5678-2345-789012345678',
    username: '210702',
    email: 'mary.kau@example.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'Mary',
    lastName: 'Kau',
    name: 'Mary Kau',
    phone: '+675 7123 4702',
    ward: 'Ward 7 Bilbil',
    nid: '1234567898',
    isApproved: false,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2026-01-22T09:10:00.000Z',
  },
  {
    id: 'usr-d0e1f2a3-b4c5-6789-3456-890123456789',
    username: '210803',
    email: 'peter.mai@example.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'Peter',
    lastName: 'Mai',
    name: 'Peter Mai',
    phone: '+675 7123 4803',
    ward: 'Ward 2 Alexishafen',
    nid: '1234567899',
    isApproved: false,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2026-02-01T11:30:00.000Z',
  },
  {
    id: 'usr-e1f2a3b4-c5d6-7890-4567-901234567890',
    username: '210904',
    email: 'helen.wai@example.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'Helen',
    lastName: 'Wai',
    name: 'Helen Wai',
    phone: '+675 7123 4904',
    ward: 'Ward 4 Bongu',
    nid: '1234567800',
    isApproved: false,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2026-02-05T13:00:00.000Z',
  },
  {
    id: 'usr-f2a3b4c5-d6e7-8901-5678-012345678901',
    username: '211005',
    email: 'david.rao@example.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'David',
    lastName: 'Rao',
    name: 'David Rao',
    phone: '+675 7123 5005',
    ward: 'Ward 6 Simbai Settlement',
    nid: '1234567801',
    isApproved: false,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2026-02-10T15:45:00.000Z',
  },
  {
    id: 'usr-a3b4c5d6-e7f8-9012-6789-123456789012',
    username: '211106',
    email: 'grace.pok@example.com',
    password: TEST_PASSWORD,
    role: 'resident',
    firstName: 'Grace',
    lastName: 'Pok',
    name: 'Grace Pok',
    phone: '+675 7123 5106',
    ward: 'Ward 1 Madang Urban',
    nid: '1234567802',
    isApproved: false,
    isActive: true,
    mfaEnabled: false,
    createdAt: '2026-02-14T08:20:00.000Z',
  },
];

export const MOCK_PROJECTS = [
  {
    id: 'prj-001-nabasa-water',
    name: 'Nabasa Community Water Supply Upgrade',
    category: 'Water & Sanitation',
    status: 'In Progress',
    budget: 185000,
    fundingSource: 'Ward Budget',
    location: 'Nabasa Village, Nabasa LLG',
    ward: 'Ward 5 Nabasa',
    dateLogged: '2025-07-10T09:00:00.000Z',
    description:
      'Rehabilitation of existing gravity-fed water system serving Nabasa and surrounding hamlets. Includes new storage tank at Kuluguma ridge and pipe extensions to 120 households.',
    loggedBy: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  },
  {
    id: 'prj-002-nabasa-road',
    name: 'Nabasa–Kuluguma Access Road Gravelling',
    category: 'Roads & Transport',
    status: 'Pending LLG',
    budget: 320000,
    fundingSource: 'DSIP',
    location: 'Nabasa to Kuluguma corridor',
    ward: 'Ward 5 Nabasa',
    dateLogged: '2025-08-02T10:30:00.000Z',
    description:
      'Gravelling and drainage works on 4.2 km feeder road linking Nabasa ward centre to Kuluguma market. Critical for cocoa and copra transport during wet season.',
    loggedBy: 'usr-b2c3d4e5-f6a7-8901-bcde-f12345678901',
  },
  {
    id: 'prj-003-bilbil-health',
    name: 'Bilbil Aid Post Staff Quarters',
    category: 'Health',
    status: 'Funded',
    budget: 95000,
    fundingSource: 'PSIP',
    location: 'Bilbil Coast, Rai Coast District',
    ward: 'Ward 7 Bilbil',
    dateLogged: '2025-06-18T08:00:00.000Z',
    description:
      'Construction of two-bedroom staff quarters for community health worker stationed at Bilbil aid post, serving coastal villages from Bongu to Tabibuga.',
    loggedBy: 'usr-b2c3d4e5-f6a7-8901-bcde-f12345678901',
  },
  {
    id: 'prj-004-alexishafen-school',
    name: 'Alexishafen Elementary Classroom Block',
    category: 'Education',
    status: 'Pending District',
    budget: 410000,
    fundingSource: 'DSIP',
    location: 'Alexishafen, Madang District',
    ward: 'Ward 2 Alexishafen',
    dateLogged: '2025-09-05T11:15:00.000Z',
    description:
      'Double classroom block with office and storeroom for Alexishafen Elementary School. Current classrooms are overcrowded with 65 pupils per room.',
    loggedBy: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  },
  {
    id: 'prj-005-bongu-solar',
    name: 'Bongu Village Solar Street Lighting',
    category: 'Energy',
    status: 'Completed',
    budget: 42000,
    fundingSource: 'Ward Budget',
    location: 'Bongu Village centre',
    ward: 'Ward 4 Bongu',
    dateLogged: '2025-04-20T07:30:00.000Z',
    description:
      'Installation of 12 solar-powered street lights along the main village path from the church to the elementary school. Completed ahead of 2025 Independence Day celebrations.',
    loggedBy: 'usr-b2c3d4e5-f6a7-8901-bcde-f12345678901',
  },
  {
    id: 'prj-006-kuluguma-market',
    name: 'Kuluguma Market Shed Rehabilitation',
    category: 'Economic Development',
    status: 'Pending WDC',
    budget: 78000,
    fundingSource: 'Ward Budget',
    location: 'Kuluguma market site',
    ward: 'Ward 3 Kuluguma',
    dateLogged: '2026-01-08T09:45:00.000Z',
    description:
      'Replacement of rusted iron roofing and timber flooring on the Kuluguma market shed. Market serves farmers from Nabasa, Simbai, and Bundi wards.',
    loggedBy: 'usr-b8c9d0e1-f2a3-4567-1234-678901234567',
  },
  {
    id: 'prj-007-simbai-bridge',
    name: 'Simbai Creek Footbridge',
    category: 'Infrastructure',
    status: 'Pending Provincial',
    budget: 560000,
    fundingSource: 'PSIP',
    location: 'Simbai Settlement, Middle Ramu',
    ward: 'Ward 6 Simbai Settlement',
    dateLogged: '2025-10-12T14:00:00.000Z',
    description:
      'Steel footbridge across Simbai Creek to provide year-round access for 800 residents during monsoon flooding. Replaces dangerous log crossing washed away in 2024.',
    loggedBy: 'usr-f2a3b4c5-d6e7-8901-5678-012345678901',
  },
  {
    id: 'prj-008-madang-urban-drainage',
    name: 'Madang Urban Ward 1 Drainage Clearing',
    category: 'Disaster Preparedness',
    status: 'In Progress',
    budget: 65000,
    fundingSource: 'Ward Budget',
    location: 'Modilon Road vicinity, Madang Town',
    ward: 'Ward 1 Madang Urban',
    dateLogged: '2025-11-01T08:00:00.000Z',
    description:
      'Clearing and desilting of open drains along Modilon Road to reduce flooding during heavy rainfall. Coordinated with Madang Urban LLG engineering team.',
    loggedBy: 'usr-a3b4c5d6-e7f8-9012-6789-123456789012',
  },
  {
    id: 'prj-009-bogia-cocoa',
    name: 'Bogia Cocoa Fermentary Support',
    category: 'Agriculture',
    status: 'Funded',
    budget: 120000,
    fundingSource: 'DSIP',
    location: 'Bogia Station, Bogia District',
    ward: 'Ward 12 Bogia Central',
    dateLogged: '2025-05-22T10:00:00.000Z',
    description:
      'Supply of fermentary drying racks, scales, and storage bins for Bogia cocoa farmers cooperative. Supports 45 registered smallholder farmers in the district.',
    loggedBy: 'usr-e5f6a7b8-c9d0-1234-ef01-345678901234',
  },
  {
    id: 'prj-010-sumkar-jetty',
    name: 'Sumkar LLG Community Jetty Extension',
    category: 'Maritime',
    status: 'Pending LLG',
    budget: 275000,
    fundingSource: 'DSIP',
    location: 'Kar Kar Island landing, Sumkar District',
    ward: 'Ward 8 Kar Kar South',
    dateLogged: '2025-08-28T13:30:00.000Z',
    description:
      'Extension of community jetty by 15 metres to accommodate larger dinghies during high tide. Improves market access for fish and garden produce traders.',
    loggedBy: 'usr-b2c3d4e5-f6a7-8901-bcde-f12345678901',
  },
  {
    id: 'prj-011-usino-health',
    name: 'Usino Aid Post Vaccine Fridge',
    category: 'Health',
    status: 'Completed',
    budget: 18000,
    fundingSource: 'Ward Budget',
    location: 'Usino Station, Usino-Bundi District',
    ward: 'Ward 9 Usino',
    dateLogged: '2025-03-15T09:00:00.000Z',
    description:
      'Solar-powered vaccine refrigerator and backup battery for Usino aid post cold chain. Enables routine immunisation outreach to remote Bundi villages.',
    loggedBy: 'usr-d4e5f6a7-b8c9-0123-def0-234567890123',
  },
  {
    id: 'prj-012-rai-coast-radio',
    name: 'Rai Coast Community Radio Equipment',
    category: 'Communications',
    status: 'Pending WDC',
    budget: 88000,
    fundingSource: 'Ward Budget',
    location: 'Tabibuga, Rai Coast District',
    ward: 'Ward 10 Tabibuga',
    dateLogged: '2026-01-25T11:00:00.000Z',
    description:
      'Two-way radio base station and handheld units for ward disaster committee and WDC coordination. Covers Tabibuga, Malala, and Bagasin areas with poor mobile coverage.',
    loggedBy: 'usr-c9d0e1f2-a3b4-5678-2345-789012345678',
  },
  {
    id: 'prj-013-nabasa-youth',
    name: 'Nabasa Youth Skills Training Centre Fit-Out',
    category: 'Youth & Sports',
    status: 'In Progress',
    budget: 145000,
    fundingSource: 'PSIP',
    location: 'Nabasa ward centre',
    ward: 'Ward 5 Nabasa',
    dateLogged: '2025-07-28T08:30:00.000Z',
    description:
      'Fit-out of existing community hall with workbenches, tools, and sewing machines for youth skills programme covering carpentry, tailoring, and basic mechanics.',
    loggedBy: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  },
  {
    id: 'prj-014-madang-sewer',
    name: 'Madang District Sewage Pump Station Repair',
    category: 'Water & Sanitation',
    status: 'Pending Provincial',
    budget: 890000,
    fundingSource: 'PSIP',
    location: 'Madang Town sewerage network',
    ward: 'Madang District',
    dateLogged: '2025-12-01T10:00:00.000Z',
    description:
      'Major repair of district sewage pump station serving Modilon Heights and Coastwatch areas. DDA coordination with Water PNG and provincial works division required.',
    loggedBy: 'usr-e5f6a7b8-c9d0-1234-ef01-345678901234',
  },
  {
    id: 'prj-015-bundi-school',
    name: 'Bundi Community School Library',
    category: 'Education',
    status: 'Funded',
    budget: 67000,
    fundingSource: 'Ward Budget',
    location: 'Bundi Village, Usino-Bundi District',
    ward: 'Ward 11 Bundi',
    dateLogged: '2025-09-18T07:45:00.000Z',
    description:
      'Construction of small library annex with shelving and reading desks for Bundi Community School. Serves 180 students from Bundi and neighbouring Middle Ramu wards.',
    loggedBy: 'usr-d0e1f2a3-b4c5-6789-3456-890123456789',
  },
  {
    id: 'prj-016-nabasa-football',
    name: 'Nabasa Ward Football Field Levelling',
    category: 'Youth & Sports',
    status: 'Pending WDC',
    budget: 35000,
    fundingSource: 'Ward Budget',
    location: 'Nabasa sports ground',
    ward: 'Ward 5 Nabasa',
    dateLogged: '2026-02-01T16:00:00.000Z',
    description:
      'Levelling and grass planting of community football field used by Nabasa United and inter-ward tournaments. WDC resolution required before ward budget release.',
    loggedBy: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  },
];

export const MOCK_REQUESTS = [
  {
    id: 'req-001-water-leak',
    category: 'Water & Sanitation',
    description:
      'Report of major leak at Nabasa main water tap near the ward office. Water running for three days and affecting supply pressure to upper hamlets.',
    status: 'In Progress',
    residentId: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    residentName: 'Lisa Numbunda',
    ward: 'Ward 5 Nabasa',
    createdAt: '2026-01-20T06:30:00.000Z',
    documents: [{ name: 'leak-photo-1.jpg', type: 'image/jpeg' }],
  },
  {
    id: 'req-002-road-pothole',
    category: 'Roads & Transport',
    description:
      'Large pothole on Nabasa–Kuluguma road at the creek crossing causing damage to PMV vehicles and delaying cocoa transport.',
    status: 'Pending',
    residentId: 'usr-b8c9d0e1-f2a3-4567-1234-678901234567',
    residentName: 'John Sare',
    ward: 'Ward 3 Kuluguma',
    createdAt: '2026-02-03T09:15:00.000Z',
    documents: [],
  },
  {
    id: 'req-003-street-light',
    category: 'Infrastructure',
    description:
      'Three solar street lights near Bilbil church are not working after recent storm. Requesting maintenance or replacement.',
    status: 'Resolved',
    residentId: 'usr-c9d0e1f2-a3b4-5678-2345-789012345678',
    residentName: 'Mary Kau',
    ward: 'Ward 7 Bilbil',
    createdAt: '2025-12-10T14:00:00.000Z',
    documents: [{ name: 'faulty-lights.jpg', type: 'image/jpeg' }],
  },
  {
    id: 'req-004-school-desks',
    category: 'Education',
    description:
      'Alexishafen Elementary School needs 30 additional desks for Grade 3 classroom. Current students sit on floor mats.',
    status: 'Pending',
    residentId: 'usr-d0e1f2a3-b4c5-6789-3456-890123456789',
    residentName: 'Peter Mai',
    ward: 'Ward 2 Alexishafen',
    createdAt: '2026-01-28T11:00:00.000Z',
    documents: [],
  },
  {
    id: 'req-005-health-outreach',
    category: 'Health',
    description:
      'Request for mobile clinic visit to Bongu outstation. No immunisation outreach since November 2025.',
    status: 'In Progress',
    residentId: 'usr-e1f2a3b4-c5d6-7890-4567-901234567890',
    residentName: 'Helen Wai',
    ward: 'Ward 4 Bongu',
    createdAt: '2026-01-15T08:45:00.000Z',
    documents: [{ name: 'community-petition.pdf', type: 'application/pdf' }],
  },
  {
    id: 'req-006-market-fees',
    category: 'Economic Development',
    description:
      'Dispute over market fee collection at Kuluguma market. Requesting WDC review of fee schedule and transparent receipting.',
    status: 'Rejected',
    residentId: 'usr-b8c9d0e1-f2a3-4567-1234-678901234567',
    residentName: 'John Sare',
    ward: 'Ward 3 Kuluguma',
    createdAt: '2025-11-20T10:30:00.000Z',
    documents: [],
  },
  {
    id: 'req-007-bridge-safety',
    category: 'Infrastructure',
    description:
      'Simbai Creek log crossing is unsafe after heavy rain. Urgent request for temporary bridge until PSIP footbridge project is completed.',
    status: 'Pending',
    residentId: 'usr-f2a3b4c5-d6e7-8901-5678-012345678901',
    residentName: 'David Rao',
    ward: 'Ward 6 Simbai Settlement',
    createdAt: '2026-02-08T07:00:00.000Z',
    documents: [
      { name: 'crossing-condition.jpg', type: 'image/jpeg' },
      { name: 'ward-letter.pdf', type: 'application/pdf' },
    ],
  },
  {
    id: 'req-008-drainage-flood',
    category: 'Disaster Preparedness',
    description:
      'Blocked drain on Modilon Road causing flooding into residential yards during last downpour. Request urgent clearing before wet season peak.',
    status: 'In Progress',
    residentId: 'usr-a3b4c5d6-e7f8-9012-6789-123456789012',
    residentName: 'Grace Pok',
    ward: 'Ward 1 Madang Urban',
    createdAt: '2026-01-05T13:20:00.000Z',
    documents: [{ name: 'flooding-photo.jpg', type: 'image/jpeg' }],
  },
  {
    id: 'req-009-youth-program',
    category: 'Youth & Sports',
    description:
      'Application to enrol 15 Nabasa youth in the ward skills training programme at the community hall. Ages 16–22.',
    status: 'Resolved',
    residentId: 'usr-a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    residentName: 'Lisa Numbunda',
    ward: 'Ward 5 Nabasa',
    createdAt: '2025-10-05T09:00:00.000Z',
    documents: [{ name: 'youth-enrolment-form.pdf', type: 'application/pdf' }],
  },
  {
    id: 'req-010-cocoa-road',
    category: 'Agriculture',
    description:
      'Request for all-weather access track maintenance to Bogia cocoa fermentary. Mud slides blocking truck access during wet season.',
    status: 'Pending',
    residentId: 'usr-d0e1f2a3-b4c5-6789-3456-890123456789',
    residentName: 'Peter Mai',
    ward: 'Ward 2 Alexishafen',
    createdAt: '2026-02-12T10:00:00.000Z',
    documents: [],
  },
  {
    id: 'req-011-aid-post-medicine',
    category: 'Health',
    description:
      'Bilbil aid post ran out of basic medicines (paracetamol, ORS). Requesting restock and explanation of supply delay.',
    status: 'Resolved',
    residentId: 'usr-c9d0e1f2-a3b4-5678-2345-789012345678',
    residentName: 'Mary Kau',
    ward: 'Ward 7 Bilbil',
    createdAt: '2025-12-22T15:30:00.000Z',
    documents: [],
  },
  {
    id: 'req-012-radio-frequency',
    category: 'Communications',
    description:
      'Request for ward disaster committee radio frequency allocation for Tabibuga area ahead of cyclone season preparedness.',
    status: 'In Progress',
    residentId: 'usr-e1f2a3b4-c5d6-7890-4567-901234567890',
    residentName: 'Helen Wai',
    ward: 'Ward 4 Bongu',
    createdAt: '2026-01-30T08:00:00.000Z',
    documents: [{ name: 'disaster-committee-list.pdf', type: 'application/pdf' }],
  },
];

export const MOCK_MEETINGS = [
  {
    id: 'mtg-001-wdc-q1',
    title: 'Ward 5 Nabasa WDC Quarterly Meeting Q1 2026',
    date: '2026-02-15',
    time: '09:00',
    agenda:
      '1. Opening prayer\n2. Minutes of previous meeting\n3. Ward budget status report\n4. Nabasa water project progress\n5. Kuluguma market shed proposal\n6. Youth skills programme update\n7. AOB',
    minutes:
      'Meeting opened at 9:05 AM with prayer by Councillor Kila. Ward budget balance of K 42,500 confirmed. Water project 60% complete. Market shed proposal referred to LLG for co-funding review. Youth programme enrolment at 28 participants.',
    attendance: ['Peter Yamau', 'James Kila', 'Lisa Numbunda', 'John Sare', 'David Rao'],
    status: 'Completed',
    ward: 'Ward 5 Nabasa',
  },
  {
    id: 'mtg-002-budget-review',
    title: 'Nabasa LLG Ward Budget Review 2026',
    date: '2026-03-01',
    time: '10:00',
    agenda:
      '1. Welcome\n2. 2026 ward budget allocations by ward\n3. DSIP project pipeline review\n4. PSIP submissions deadline\n5. Reporting requirements',
    minutes: '',
    attendance: ['Sarah Mathew', 'James Kila', 'Peter Yamau'],
    status: 'Scheduled',
    ward: 'Nabasa LLG',
  },
  {
    id: 'mtg-003-emergency',
    title: 'Emergency WDC Meeting – Simbai Creek Flooding',
    date: '2026-01-25',
    time: '14:00',
    agenda:
      '1. Situation report on Simbai Creek crossing\n2. Temporary access options\n3. PSIP footbridge project escalation\n4. Disaster committee activation',
    minutes:
      'WDC resolved to write to DDA requesting emergency bridge materials. Provincial PSIP coordinator notified. Community advised to avoid crossing until further notice.',
    attendance: ['Peter Yamau', 'James Kila', 'David Rao', 'Helen Wai'],
    status: 'Completed',
    ward: 'Ward 6 Simbai Settlement',
  },
  {
    id: 'mtg-004-project-prioritisation',
    title: 'Madang District DSIP Project Prioritisation Workshop',
    date: '2026-02-28',
    time: '08:30',
    agenda:
      '1. DSIP 2026 funding envelope\n2. Ward project submissions review\n3. Priority scoring methodology\n4. Draft district project list',
    minutes: '',
    attendance: ['Michael Taki', 'James Kila', 'Sarah Mathew'],
    status: 'Scheduled',
    ward: 'Madang District',
  },
  {
    id: 'mtg-005-youth-consultation',
    title: 'Nabasa Youth Consultation – Skills Training Needs',
    date: '2025-09-20',
    time: '11:00',
    agenda:
      '1. Youth demographics\n2. Skills gap survey results\n3. Proposed training modules\n4. Facility requirements\n5. Funding options',
    minutes:
      'Youth identified carpentry, tailoring, and small engine repair as top priorities. WDC agreed to pursue PSIP funding for training centre fit-out. Lisa Numbunda volunteered to coordinate enrolment.',
    attendance: ['Lisa Numbunda', 'Peter Yamau', 'Grace Pok', 'David Rao'],
    status: 'Completed',
    ward: 'Ward 5 Nabasa',
  },
  {
    id: 'mtg-006-cancelled',
    title: 'Bilbil Ward Development Committee Meeting',
    date: '2026-01-10',
    time: '09:00',
    agenda: '1. Aid post update\n2. Solar lighting maintenance\n3. Coastal erosion concerns',
    minutes: '',
    attendance: [],
    status: 'Cancelled',
    ward: 'Ward 7 Bilbil',
  },
  {
    id: 'mtg-007-in-progress',
    title: 'Provincial PSIP Coordination Meeting',
    date: '2026-02-18',
    time: '13:00',
    agenda:
      '1. PSIP 2026 approved projects\n2. Nabasa water and youth centre status\n3. Simbai footbridge timeline\n4. Reporting to PEC',
    minutes: 'Meeting in progress. Nabasa projects noted as on track.',
    attendance: ['Grace Kaupa', 'Michael Taki', 'Sarah Mathew', 'Peter Yamau'],
    status: 'In Progress',
    ward: 'Madang Province',
  },
];

export const MOCK_RESOLUTIONS = [
  {
    id: 'res-001-market-shed',
    title: 'Approval of Kuluguma Market Shed Rehabilitation',
    meetingId: 'mtg-001-wdc-q1',
    description:
      'WDC resolves to approve the Kuluguma market shed rehabilitation project at estimated cost of K 78,000 from ward budget, subject to LLG co-funding confirmation.',
    status: 'Approved',
    votesFor: 4,
    votesAgainst: 0,
    createdAt: '2026-02-15T11:30:00.000Z',
  },
  {
    id: 'res-002-football-field',
    title: 'Nabasa Football Field Levelling Project',
    meetingId: 'mtg-001-wdc-q1',
    description:
      'WDC resolves to submit Nabasa football field levelling project (K 35,000) for inclusion in 2026 ward budget expenditure.',
    status: 'Pending',
    votesFor: 3,
    votesAgainst: 1,
    createdAt: '2026-02-15T11:45:00.000Z',
  },
  {
    id: 'res-003-simbai-bridge',
    title: 'Emergency Request for Simbai Creek Crossing',
    meetingId: 'mtg-003-emergency',
    description:
      'WDC resolves to formally request DDA emergency assistance for temporary bridge materials at Simbai Creek crossing pending PSIP footbridge completion.',
    status: 'Approved',
    votesFor: 4,
    votesAgainst: 0,
    createdAt: '2026-01-25T15:00:00.000Z',
  },
  {
    id: 'res-004-youth-centre',
    title: 'PSIP Submission for Nabasa Youth Skills Centre',
    meetingId: 'mtg-005-youth-consultation',
    description:
      'WDC resolves to endorse PSIP submission for Nabasa Youth Skills Training Centre fit-out at K 145,000 for provincial consideration.',
    status: 'Approved',
    votesFor: 4,
    votesAgainst: 0,
    createdAt: '2025-09-20T12:30:00.000Z',
  },
  {
    id: 'res-005-market-fees',
    title: 'Kuluguma Market Fee Schedule Review',
    meetingId: 'mtg-001-wdc-q1',
    description:
      'Proposal to reduce daily market fees for small-scale vegetable vendors from K 2 to K 1. Rejected due to insufficient ward revenue projections.',
    status: 'Rejected',
    votesFor: 1,
    votesAgainst: 3,
    createdAt: '2026-02-15T12:00:00.000Z',
  },
  {
    id: 'res-006-radio-equipment',
    title: 'Ward Disaster Radio Equipment Procurement',
    meetingId: 'mtg-002-budget-review',
    description:
      'Draft resolution to allocate K 88,000 from ward budget for Rai Coast community radio equipment pending LLG budget review meeting.',
    status: 'Pending',
    votesFor: 0,
    votesAgainst: 0,
    createdAt: '2026-02-01T09:00:00.000Z',
  },
];

export const MOCK_ANNOUNCEMENTS = [
  {
    id: 'ann-001-water-shutdown',
    title: 'Scheduled Water Shutdown – Nabasa',
    content:
      'Nabasa community water supply will be shut down on Saturday 22 February 2026 from 6:00 AM to 2:00 PM for tank installation works at Kuluguma ridge. Please store water in advance.',
    priority: 'high',
    targetAudience: 'residents',
    ward: 'Ward 5 Nabasa',
    createdBy: 'James Kila',
    createdAt: '2026-02-18T08:00:00.000Z',
    isActive: true,
  },
  {
    id: 'ann-002-dsip-deadline',
    title: 'DSIP 2026 Project Submission Deadline',
    content:
      'All ward councillors must submit DSIP project proposals to the Madang DDA office by 28 February 2026. Late submissions will not be considered for the 2026 funding round.',
    priority: 'high',
    targetAudience: 'councillors',
    ward: 'Madang District',
    createdBy: 'Michael Taki',
    createdAt: '2026-02-01T10:00:00.000Z',
    isActive: true,
  },
  {
    id: 'ann-003-youth-enrolment',
    title: 'Youth Skills Programme – Enrolment Open',
    content:
      'Enrolment is open for the Nabasa Youth Skills Training Programme at the ward community hall. Courses in carpentry, tailoring, and basic mechanics start 1 March 2026. Contact Lisa Numbunda at the ward office.',
    priority: 'medium',
    targetAudience: 'residents',
    ward: 'Ward 5 Nabasa',
    createdBy: 'Peter Yamau',
    createdAt: '2026-02-10T09:30:00.000Z',
    isActive: true,
  },
  {
    id: 'ann-004-immunisation',
    title: 'Child Immunisation Outreach – Bilbil Coast',
    content:
      'Madang Provincial Health will conduct child immunisation outreach at Bilbil aid post on Wednesday 5 March 2026, 8:00 AM – 3:00 PM. Bring child health record books.',
    priority: 'medium',
    targetAudience: 'residents',
    ward: 'Ward 7 Bilbil',
    createdBy: 'Sarah Mathew',
    createdAt: '2026-02-14T11:00:00.000Z',
    isActive: true,
  },
  {
    id: 'ann-005-system-maintenance',
    title: 'System Maintenance Notice',
    content:
      'Community ConnectHub will undergo scheduled maintenance on Sunday 23 February 2026 from 11:00 PM to 2:00 AM. Online services may be temporarily unavailable.',
    priority: 'low',
    targetAudience: 'all',
    ward: 'All Wards',
    createdBy: 'Admin User',
    createdAt: '2026-02-17T07:00:00.000Z',
    isActive: true,
  },
  {
    id: 'ann-006-wdc-meeting',
    title: 'WDC Meeting Reminder – Ward 5 Nabasa',
    content:
      'Reminder: Ward 5 Nabasa WDC quarterly meeting scheduled for Saturday 15 February 2026 at 9:00 AM at the ward office. All ward committee members please attend.',
    priority: 'medium',
    targetAudience: 'wdc',
    ward: 'Ward 5 Nabasa',
    createdBy: 'Peter Yamau',
    createdAt: '2026-02-12T14:00:00.000Z',
    isActive: false,
  },
];

export const MOCK_AUDIT_LOGS = [
  {
    id: 'log-001-login-lisa',
    action: 'USER_LOGIN',
    user: 'Lisa Numbunda',
    role: 'resident',
    timestamp: '2026-02-18T07:15:00.000Z',
    details: 'Successful login from Nabasa ward via web application.',
  },
  {
    id: 'log-002-approve-councillor',
    action: 'USER_APPROVED',
    user: 'James Kila',
    role: 'system_admin',
    timestamp: '2025-05-01T09:30:00.000Z',
    details: 'System admin approved councillor account registration for Ward 5 Nabasa.',
  },
  {
    id: 'log-003-project-created',
    action: 'PROJECT_CREATED',
    user: 'Lisa Numbunda',
    role: 'resident',
    timestamp: '2025-07-10T09:05:00.000Z',
    details: 'Created project "Nabasa Community Water Supply Upgrade" (prj-001-nabasa-water).',
  },
  {
    id: 'log-004-project-status',
    action: 'PROJECT_STATUS_UPDATED',
    user: 'Peter Yamau',
    role: 'wdc_chairman',
    timestamp: '2025-08-15T10:00:00.000Z',
    details: 'Updated project prj-001-nabasa-water status from "Funded" to "In Progress".',
  },
  {
    id: 'log-005-request-assigned',
    action: 'REQUEST_ASSIGNED',
    user: 'James Kila',
    role: 'councillor',
    timestamp: '2026-01-21T08:00:00.000Z',
    details: 'Assigned request req-001-water-leak to ward works committee for inspection.',
  },
  {
    id: 'log-006-meeting-minutes',
    action: 'MEETING_MINUTES_SAVED',
    user: 'Peter Yamau',
    role: 'wdc_chairman',
    timestamp: '2026-02-15T12:30:00.000Z',
    details: 'Saved minutes for WDC Q1 2026 meeting (mtg-001-wdc-q1).',
  },
  {
    id: 'log-007-resolution-approved',
    action: 'RESOLUTION_APPROVED',
    user: 'Peter Yamau',
    role: 'wdc_chairman',
    timestamp: '2026-02-15T11:35:00.000Z',
    details: 'Resolution res-001-market-shed approved with 4 votes for, 0 against.',
  },
  {
    id: 'log-008-pending-registration',
    action: 'REGISTRATION_PENDING',
    user: 'John Sare',
    role: 'resident',
    timestamp: '2026-01-18T06:50:00.000Z',
    details: 'New resident registration submitted for Ward 3 Kuluguma. Awaiting LLG admin approval.',
  },
  {
    id: 'log-009-announcement-published',
    action: 'ANNOUNCEMENT_PUBLISHED',
    user: 'James Kila',
    role: 'councillor',
    timestamp: '2026-02-18T08:05:00.000Z',
    details: 'Published high-priority announcement "Scheduled Water Shutdown – Nabasa" to Ward 5 residents.',
  },
  {
    id: 'log-010-dsip-export',
    action: 'REPORT_EXPORTED',
    user: 'Michael Taki',
    role: 'dda_officer',
    timestamp: '2026-02-10T14:30:00.000Z',
    details: 'Exported DSIP 2026 project pipeline report for Madang District (16 projects).',
  },
];

const INITIAL_DATA = {
  users: MOCK_USERS,
  projects: MOCK_PROJECTS,
  requests: MOCK_REQUESTS,
  meetings: MOCK_MEETINGS,
  resolutions: MOCK_RESOLUTIONS,
  announcements: MOCK_ANNOUNCEMENTS,
  auditLogs: MOCK_AUDIT_LOGS,
};

export default INITIAL_DATA;
